[package]
name = "barcode_pdf_pc"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
pdf2image = "0.1.2"
rxing = "0.6.4"
serde = "1.0.216"
serde_json = "1.0.134"
tao = "0.31.0"
tray-icon = "0.19.2"
